/**
 * @file texts.ts
 * @description Centralização de textos do portal TV Russas para fins de acessibilidade,
 * padronização de nomenclatura e internacionalização-ready (i18n), eliminando
 * strings hardcoded em arquivos JSX de acordo com as regras de portabilidade.
 */

export const TEXTS = {
  brand: {
    name: "TV Russas",
    panel: "Painel Editorial",
    slogan: "Informação com credibilidade e agilidade em Russas e região.",
    sloganFooter: "O portal de notícias da sua cidade. Informação com credibilidade e agilidade.",
    rights: "Todos os direitos reservados.",
    acervo: "FOTO: REPRODUÇÃO / ACERVO TV RUSSAS",
  },
  navigation: {
    home: "Página Inicial",
    inicio: "Início",
    menu: "MENU",
    categories: "Categorias",
    navigation: "Navegação",
    columnists: "Colunistas",
    reporter: "Você Repórter",
    verTodas: "Ver todas",
    restrictAccess: "Acesso Restrito",
    contact: "Contato",
  },
  admin: {
    dashboard: "Dashboard",
    news: "Notícias",
    categories: "Categorias",
    users: "Usuários",
    settings: "Configurações",
    auditoria: "Logs de Auditoria",
    reporterSub: "Denúncias, relatos e fotos enviados em tempo real pelos leitores do portal",
    suggestionsReceived: "Sugestões Recebidas",
    awaitingReview: "Aguardando Revisão",
    readReports: "Relatos Lidos",
    withMedia: "Com Anexo de Mídia",
    loadingSuggestions: "Carregando sugestões...",
    noReportsFound: "Nenhum relato encontrado nesta categoria",
    sender: "Remetente",
    phone: "Telefone",
    citizenReport: "Relato do Cidadão",
    evidenceMedia: "Evidência / Mídia Anexada",
    markAsRead: "Marcar como Lida",
    markAsArchived: "Marcar como Arquivada",
    statusAll: "Todas",
    statusPending: "Pendentes",
    statusRead: "Lidas",
    statusArchived: "Arquivadas",
    analyzing: "Analisar",
    stable: "Estável",
    // Analytics
    loadingStats: "Carregando dados estatísticos...",
    noHistoryData: "Nenhum dado histórico disponível",
    views: "views",
    // Admin dashboard
    editorialRhythm: "Ritmo Editorial",
    newsFlowTrack: "Acompanhamento de fluxo de notícias",
    noPublicationsPeriod: "Sem publicações no período",
    noPubsShortText: "Nenhuma matéria foi publicada na plataforma nos últimos ",
    writeNews: "Escrever notícia",
    totalPublished: "Total Publicado",
    recordDay: "Dia Recorde",
    trend: "Tendência",
    publications: "Publicações:",
    dailyVariation: "Variação diária:",
    leadingCategory: "Categoria líder:",
    editorialRedaction: "Redação",
    publishedNews: "Notícias publicadas",
    totalViews: "Visualizações totais",
    likesReceived: "Curtidas recebidas",
    pendingSuggestions: "Sugestões pendentes",
    mostRead: "Mais Lidas",
    trending: "Em Alta",
    loadingEditorialIntel: "Carregando inteligência editorial...",
    noAccumulatedAccess: "Nenhum dado de acesso acumulado ainda.",
    noRecentTrafficPeak: "Nenhum pico de tráfego detectado recentemente.",
    editorialTimeline: "Timeline Editorial",
    platformActionTrack: "Acompanhamento de ações na plataforma",
    viewFullAudit: "Ver auditoria completa",
    reader: "Leitor: ",
    // NoticiaEditorForm
    editMode: "Modo de edição editorial.",
    createMode: "Modo de criação editorial.",
    savingDraft: "Salvando rascunho...",
    draftSaved: "Rascunho salvo localmente",
    writeMatter: "Escrever Matéria",
    editMatter: "Editar Matéria",
    newsContentEmpty: "O conteúdo da notícia não pode estar vazio.",
    coverRequired: "A imagem de capa é obrigatória.",
    source: "Fonte",
    sourceColon: "Fonte:",
    publishedBy: "Publicado por:",
    publication: "Publicação",
    feedClassification: "Classificação de Feed",
    standardFeedNews: "Notícia padrão no feed cronológico.",
    bannerHighlight: "Destaque do Banner",
    bannerHighlightSub: "Aparecerá no banner principal (máx. 3).",
    matterCover: "Capa da Matéria ",
    change: "Trocar",
    clickUploadCover: "Clique para enviar a capa",
    organization: "Organização",
    slugSeo: "Slug (URL SEO)",
    category: "Categoria ",
    select: "Selecione...",
    matterAuthor: "Autor da Matéria",
    defaultAuthor: "Redação TV Russas",
    optionalTags: "Tags Opcionais",
    words: "Palavras",
    readTimeLabel: "Tempo Leitura",
    bannerMaxAlert: "O banner inicial da página suporta no máximo ",
    confirmReplacement: "Confirmar Substituição",
    manageNewsDescription: "Gerencie as matérias, destaques, coberturas e publicações editoriais do portal",
    newNews: "Nova Notícia",
    activeHighlights: "Destaques Ativos",
    totalViewsMetric: "Views Totais",
    allCategoriesFilter: "Todas as categorias",
    allClassificationsFilter: "Todas as classificações",
    activeHighlightsFilter: "Destaques do Banner",
    onlyLatestFilter: "Apenas Últimas Notícias",
    processingEditorialData: "Processando dados editoriais...",
    coverLabel: "Capa",
    categoryLabel: "Categoria",
    authorLabel: "Autor",
    dateLabel: "Data",
    viewsLabel: "Views",
    statusLabel: "Status",
    noNewsMatchingFilters: "Nenhuma matéria encontrada com os filtros selecionados",
    publishedStatus: "Publicada",
    editAction: "Editar",
    displaying: "Exibindo ",
    previous: "Anterior",
    next: "Próximo",
  },
  reporter: {
    heroTitle: "Você Repórter",
    heroSubtitle: "Envie denúncias, sugestões de pautas, vídeos e fotos de acontecimentos importantes da sua cidade e região.",
    secureChannel: "Canal Seguro",
    identityPreserved: "Identidade Preservada",
    fastResponse: "Resposta Rápida",
    fullName: "Nome completo",
    fullNamePlaceholder: "Como devemos te chamar?",
    emailPlaceholder: "Para receber atualizações",
    whatsappPhone: "WhatsApp ou Telefone",
    attachMedia: "Anexar Mídia (Foto, Vídeo ou PDF)",
    dragDropHere: "Arraste e solte seu arquivo aqui",
    clickBrowseDevice: "ou clique para procurar no seu dispositivo (Max 50MB)",
    eventReport: "Relato do Acontecimento",
    eventReportPlaceholder: "Descreva o acontecimento com o máximo de detalhes possível: O que aconteceu? Onde? Quando? Quem estava envolvido?",
    charCounter: "caracteres digitados",
    truthDeclaration: "Declaro que as informações são verdadeiras",
    truthDeclarationSub: " e autorizo a equipe de jornalismo da TV Russas a investigar, editar e publicar este relato de acordo com os critérios editoriais.",
    sending: "Enviando...",
    sendSecureInfo: "Enviar Informação Segura",
    receivedSuccess: "Relato Recebido com Sucesso!",
    receivedSuccessSub: "Nossa equipe de jornalismo já foi notificada e está analisando sua informação. Entraremos em contato caso precisemos de mais detalhes.",
    sendNewInfo: "Enviar nova informação",
    commitmentTitle: "Compromisso TV Russas",
    commitmentItem1: "Sua identidade e dados pessoais jamais serão publicados sem autorização expressa.",
    commitmentItem2: "Todo material recebido passa por checagem rigorosa de nossa redação.",
    commitmentItem3: "Você está protegido pela lei de sigilo da fonte jornalística.",
    whatToSend: "O que enviar?",
    faqDenuncias: "Denúncias",
    faqDenunciasDesc: "Problemas de infraestrutura, buracos, falta de água, iluminação, ou descaso público.",
    faqOcorrencias: "Ocorrências",
    faqOcorrenciasDesc: "Acidentes, incêndios, ou movimentação policial na sua rua ou bairro.",
    faqEventos: "Eventos Locais",
    faqEventosDesc: "Ações da comunidade, feiras, esportes amadores e festividades.",
  },
  search: {
    editorialSearch: "Busca Editorial",
    didYouMean: "Você quis dizer: ",
    noNewsFound: "Nenhuma matéria encontrada",
    tryOtherTerms: "Tente buscar por outros termos ou verifique a grafia.",
    resultsFor: "Resultados para ",
    noNewsFoundFor: "Nenhuma notícia encontrada para ",
  },
  newsletter: {
    success: "Inscrição realizada com sucesso!",
    placeholder: "Seu melhor e-mail",
    subscribing: "Inscritos...",
    subscribe: "Inscrever-se",
  },
  feedback: {
    thankYou: "Obrigado pelo seu feedback!",
    subText: "Sua opinião ajuda a melhorar nosso conteúdo.",
    title: "O que você achou desta matéria?",
    excellent: "Excelente",
    couldImprove: "Poderia melhorar",
  },
  actions: {
    save: "Salvar",
    publish: "Publicar Matéria",
    edit: "Editar",
    delete: "Excluir",
    cancel: "Cancelar",
    back: "Voltar",
    close: "Fechar",
    search: "Buscar",
  },
  widgets: {
    trending: "Em Alta",
    mostRead: "Mais Lidas",
    related: "Leia Também",
    subjects: "ASSUNTOS:",
    shareTitle: "Compartilhe esta matéria:",
  },
  common: {
    por: "Por",
    readTime: "min de leitura",
    views: "visualizações",
    noNews: "Nenhuma notícia encontrada nesta categoria.",
    categoryTitle: "Categoria: ",
    ceara: "Ceará",
    russas: "Russas",
  }
};
